/* ============================================
   Quick, Decide! — 345 Quick Draw Categories
   Order matches doodleNet model output indices
   ============================================ */

const CATEGORIES = [
    { name: "flashlight", displayName: "Flashlight", emoji: "🔦", difficulty: "easy" },
    { name: "belt", displayName: "Belt", emoji: "👔", difficulty: "medium" },
    { name: "mushroom", displayName: "Mushroom", emoji: "🍄", difficulty: "easy" },
    { name: "pond", displayName: "Pond", emoji: "💧", difficulty: "medium" },
    { name: "strawberry", displayName: "Strawberry", emoji: "🍓", difficulty: "easy" },
    { name: "pineapple", displayName: "Pineapple", emoji: "🍍", difficulty: "easy" },
    { name: "sun", displayName: "Sun", emoji: "☀️", difficulty: "easy" },
    { name: "cow", displayName: "Cow", emoji: "🐄", difficulty: "medium" },
    { name: "ear", displayName: "Ear", emoji: "👂", difficulty: "medium" },
    { name: "bush", displayName: "Bush", emoji: "🌿", difficulty: "medium" },
    { name: "pliers", displayName: "Pliers", emoji: "🔧", difficulty: "hard" },
    { name: "watermelon", displayName: "Watermelon", emoji: "🍉", difficulty: "easy" },
    { name: "apple", displayName: "Apple", emoji: "🍎", difficulty: "easy" },
    { name: "baseball", displayName: "Baseball", emoji: "⚾", difficulty: "easy" },
    { name: "feather", displayName: "Feather", emoji: "🪶", difficulty: "medium" },
    { name: "shoe", displayName: "Shoe", emoji: "👟", difficulty: "easy" },
    { name: "leaf", displayName: "Leaf", emoji: "🍃", difficulty: "easy" },
    { name: "lollipop", displayName: "Lollipop", emoji: "🍭", difficulty: "easy" },
    { name: "crown", displayName: "Crown", emoji: "👑", difficulty: "easy" },
    { name: "ocean", displayName: "Ocean", emoji: "🌊", difficulty: "medium" },
    { name: "horse", displayName: "Horse", emoji: "🐴", difficulty: "medium" },
    { name: "mountain", displayName: "Mountain", emoji: "⛰️", difficulty: "easy" },
    { name: "mosquito", displayName: "Mosquito", emoji: "🦟", difficulty: "hard" },
    { name: "mug", displayName: "Mug", emoji: "☕", difficulty: "easy" },
    { name: "hospital", displayName: "Hospital", emoji: "🏥", difficulty: "medium" },
    { name: "saw", displayName: "Saw", emoji: "🪚", difficulty: "medium" },
    { name: "castle", displayName: "Castle", emoji: "🏰", difficulty: "medium" },
    { name: "angel", displayName: "Angel", emoji: "👼", difficulty: "medium" },
    { name: "underwear", displayName: "Underwear", emoji: "🩲", difficulty: "easy" },
    { name: "traffic_light", displayName: "Traffic Light", emoji: "🚦", difficulty: "easy" },
    { name: "cruise_ship", displayName: "Cruise Ship", emoji: "🚢", difficulty: "medium" },
    { name: "marker", displayName: "Marker", emoji: "🖊️", difficulty: "medium" },
    { name: "blueberry", displayName: "Blueberry", emoji: "🫐", difficulty: "easy" },
    { name: "flamingo", displayName: "Flamingo", emoji: "🦩", difficulty: "medium" },
    { name: "face", displayName: "Face", emoji: "😀", difficulty: "easy" },
    { name: "hockey_stick", displayName: "Hockey Stick", emoji: "🏒", difficulty: "medium" },
    { name: "bucket", displayName: "Bucket", emoji: "🪣", difficulty: "easy" },
    { name: "campfire", displayName: "Campfire", emoji: "🔥", difficulty: "medium" },
    { name: "asparagus", displayName: "Asparagus", emoji: "✏️", difficulty: "hard" },
    { name: "skateboard", displayName: "Skateboard", emoji: "🛹", difficulty: "medium" },
    { name: "door", displayName: "Door", emoji: "🚪", difficulty: "easy" },
    { name: "suitcase", displayName: "Suitcase", emoji: "🧳", difficulty: "easy" },
    { name: "skull", displayName: "Skull", emoji: "💀", difficulty: "medium" },
    { name: "cloud", displayName: "Cloud", emoji: "☁️", difficulty: "easy" },
    { name: "paint_can", displayName: "Paint Can", emoji: "🪣", difficulty: "medium" },
    { name: "hockey_puck", displayName: "Hockey Puck", emoji: "🏒", difficulty: "easy" },
    { name: "steak", displayName: "Steak", emoji: "🥩", difficulty: "medium" },
    { name: "house_plant", displayName: "House Plant", emoji: "🪴", difficulty: "easy" },
    { name: "sleeping_bag", displayName: "Sleeping Bag", emoji: "🛏️", difficulty: "medium" },
    { name: "bench", displayName: "Bench", emoji: "🪑", difficulty: "easy" },
    { name: "snowman", displayName: "Snowman", emoji: "⛄", difficulty: "easy" },
    { name: "arm", displayName: "Arm", emoji: "💪", difficulty: "medium" },
    { name: "crayon", displayName: "Crayon", emoji: "🖍️", difficulty: "easy" },
    { name: "fan", displayName: "Fan", emoji: "🌀", difficulty: "medium" },
    { name: "shovel", displayName: "Shovel", emoji: "✏️", difficulty: "medium" },
    { name: "leg", displayName: "Leg", emoji: "🦵", difficulty: "medium" },
    { name: "washing_machine", displayName: "Washing Machine", emoji: "✏️", difficulty: "medium" },
    { name: "harp", displayName: "Harp", emoji: "✏️", difficulty: "hard" },
    { name: "toothbrush", displayName: "Toothbrush", emoji: "🪥", difficulty: "easy" },
    { name: "tree", displayName: "Tree", emoji: "🌳", difficulty: "easy" },
    { name: "bear", displayName: "Bear", emoji: "🐻", difficulty: "medium" },
    { name: "rake", displayName: "Rake", emoji: "✏️", difficulty: "medium" },
    { name: "megaphone", displayName: "Megaphone", emoji: "📢", difficulty: "medium" },
    { name: "knee", displayName: "Knee", emoji: "🦵", difficulty: "hard" },
    { name: "guitar", displayName: "Guitar", emoji: "🎸", difficulty: "medium" },
    { name: "calculator", displayName: "Calculator", emoji: "🧮", difficulty: "medium" },
    { name: "hurricane", displayName: "Hurricane", emoji: "🌀", difficulty: "medium" },
    { name: "grapes", displayName: "Grapes", emoji: "🍇", difficulty: "easy" },
    { name: "paintbrush", displayName: "Paintbrush", emoji: "🖌️", difficulty: "easy" },
    { name: "couch", displayName: "Couch", emoji: "🛋️", difficulty: "medium" },
    { name: "nose", displayName: "Nose", emoji: "👃", difficulty: "medium" },
    { name: "square", displayName: "Square", emoji: "⬜", difficulty: "easy" },
    { name: "wristwatch", displayName: "Wristwatch", emoji: "⌚", difficulty: "medium" },
    { name: "penguin", displayName: "Penguin", emoji: "🐧", difficulty: "easy" },
    { name: "bridge", displayName: "Bridge", emoji: "🌉", difficulty: "medium" },
    { name: "octagon", displayName: "Octagon", emoji: "🛑", difficulty: "easy" },
    { name: "submarine", displayName: "Submarine", emoji: "🚢", difficulty: "medium" },
    { name: "screwdriver", displayName: "Screwdriver", emoji: "🪛", difficulty: "medium" },
    { name: "rollerskates", displayName: "Roller Skates", emoji: "⛸️", difficulty: "hard" },
    { name: "ladder", displayName: "Ladder", emoji: "🪜", difficulty: "easy" },
    { name: "wine_bottle", displayName: "Wine Bottle", emoji: "🍾", difficulty: "easy" },
    { name: "cake", displayName: "Cake", emoji: "🎂", difficulty: "easy" },
    { name: "bracelet", displayName: "Bracelet", emoji: "📿", difficulty: "medium" },
    { name: "broom", displayName: "Broom", emoji: "🧹", difficulty: "medium" },
    { name: "yoga", displayName: "Yoga", emoji: "🧘", difficulty: "hard" },
    { name: "finger", displayName: "Finger", emoji: "☝️", difficulty: "medium" },
    { name: "fish", displayName: "Fish", emoji: "🐟", difficulty: "easy" },
    { name: "line", displayName: "Line", emoji: "➖", difficulty: "easy" },
    { name: "truck", displayName: "Truck", emoji: "🚚", difficulty: "medium" },
    { name: "snake", displayName: "Snake", emoji: "🐍", difficulty: "easy" },
    { name: "bus", displayName: "Bus", emoji: "🚌", difficulty: "medium" },
    { name: "stitches", displayName: "Stitches", emoji: "🩹", difficulty: "hard" },
    { name: "snorkel", displayName: "Snorkel", emoji: "🤿", difficulty: "medium" },
    { name: "shorts", displayName: "Shorts", emoji: "🩳", difficulty: "easy" },
    { name: "bowtie", displayName: "Bowtie", emoji: "🎀", difficulty: "easy" },
    { name: "pickup_truck", displayName: "Pickup Truck", emoji: "🛻", difficulty: "medium" },
    { name: "tooth", displayName: "Tooth", emoji: "🦷", difficulty: "easy" },
    { name: "snail", displayName: "Snail", emoji: "🐌", difficulty: "easy" },
    { name: "foot", displayName: "Foot", emoji: "🦶", difficulty: "medium" },
    { name: "crab", displayName: "Crab", emoji: "🦀", difficulty: "medium" },
    { name: "school_bus", displayName: "School Bus", emoji: "🚌", difficulty: "easy" },
    { name: "train", displayName: "Train", emoji: "🚂", difficulty: "medium" },
    { name: "dresser", displayName: "Dresser", emoji: "🗄️", difficulty: "medium" },
    { name: "sock", displayName: "Sock", emoji: "🧦", difficulty: "easy" },
    { name: "tractor", displayName: "Tractor", emoji: "🚜", difficulty: "medium" },
    { name: "map", displayName: "Map", emoji: "🗺️", difficulty: "hard" },
    { name: "hedgehog", displayName: "Hedgehog", emoji: "🦔", difficulty: "medium" },
    { name: "coffee_cup", displayName: "Coffee Cup", emoji: "☕", difficulty: "easy" },
    { name: "computer", displayName: "Computer", emoji: "💻", difficulty: "medium" },
    { name: "matches", displayName: "Matches", emoji: "✏️", difficulty: "medium" },
    { name: "beard", displayName: "Beard", emoji: "🧔", difficulty: "medium" },
    { name: "frog", displayName: "Frog", emoji: "🐸", difficulty: "easy" },
    { name: "crocodile", displayName: "Crocodile", emoji: "🐊", difficulty: "medium" },
    { name: "bathtub", displayName: "Bathtub", emoji: "🛁", difficulty: "easy" },
    { name: "rain", displayName: "Rain", emoji: "🌧️", difficulty: "easy" },
    { name: "moon", displayName: "Moon", emoji: "🌙", difficulty: "easy" },
    { name: "bee", displayName: "Bee", emoji: "🐝", difficulty: "medium" },
    { name: "knife", displayName: "Knife", emoji: "🔪", difficulty: "easy" },
    { name: "boomerang", displayName: "Boomerang", emoji: "🪃", difficulty: "medium" },
    { name: "lighthouse", displayName: "Lighthouse", emoji: "🏗️", difficulty: "medium" },
    { name: "chandelier", displayName: "Chandelier", emoji: "✏️", difficulty: "hard" },
    { name: "jail", displayName: "Jail", emoji: "✏️", difficulty: "medium" },
    { name: "pool", displayName: "Pool", emoji: "🏊", difficulty: "medium" },
    { name: "stethoscope", displayName: "Stethoscope", emoji: "🩺", difficulty: "medium" },
    { name: "frying_pan", displayName: "Frying Pan", emoji: "🍳", difficulty: "easy" },
    { name: "cell_phone", displayName: "Cell Phone", emoji: "📱", difficulty: "easy" },
    { name: "binoculars", displayName: "Binoculars", emoji: "🔭", difficulty: "medium" },
    { name: "purse", displayName: "Purse", emoji: "👛", difficulty: "easy" },
    { name: "lantern", displayName: "Lantern", emoji: "🏮", difficulty: "medium" },
    { name: "birthday_cake", displayName: "Birthday Cake", emoji: "🎂", difficulty: "easy" },
    { name: "clarinet", displayName: "Clarinet", emoji: "🎵", difficulty: "hard" },
    { name: "palm_tree", displayName: "Palm Tree", emoji: "🌴", difficulty: "easy" },
    { name: "aircraft_carrier", displayName: "Aircraft Carrier", emoji: "🚢", difficulty: "hard" },
    { name: "vase", displayName: "Vase", emoji: "🏺", difficulty: "easy" },
    { name: "eraser", displayName: "Eraser", emoji: "✏️", difficulty: "medium" },
    { name: "shark", displayName: "Shark", emoji: "🦈", difficulty: "medium" },
    { name: "skyscraper", displayName: "Skyscraper", emoji: "🏙️", difficulty: "medium" },
    { name: "bicycle", displayName: "Bicycle", emoji: "🚲", difficulty: "medium" },
    { name: "sink", displayName: "Sink", emoji: "✏️", difficulty: "easy" },
    { name: "teapot", displayName: "Teapot", emoji: "🫖", difficulty: "easy" },
    { name: "circle", displayName: "Circle", emoji: "⭕", difficulty: "easy" },
    { name: "tornado", displayName: "Tornado", emoji: "🌪️", difficulty: "medium" },
    { name: "bird", displayName: "Bird", emoji: "🐦", difficulty: "easy" },
    { name: "stereo", displayName: "Stereo", emoji: "📻", difficulty: "medium" },
    { name: "mouth", displayName: "Mouth", emoji: "👄", difficulty: "easy" },
    { name: "key", displayName: "Key", emoji: "🔑", difficulty: "easy" },
    { name: "hot_dog", displayName: "Hot Dog", emoji: "🌭", difficulty: "easy" },
    { name: "spoon", displayName: "Spoon", emoji: "🥄", difficulty: "easy" },
    { name: "laptop", displayName: "Laptop", emoji: "💻", difficulty: "easy" },
    { name: "cup", displayName: "Cup", emoji: "🥤", difficulty: "easy" },
    { name: "bottlecap", displayName: "Bottle Cap", emoji: "✏️", difficulty: "medium" },
    { name: "The_Great_Wall_of_China", displayName: "Great Wall of China", emoji: "🏯", difficulty: "hard" },
    { name: "The_Mona_Lisa", displayName: "Mona Lisa", emoji: "🖼️", difficulty: "hard" },
    { name: "smiley_face", displayName: "Smiley Face", emoji: "😊", difficulty: "easy" },
    { name: "waterslide", displayName: "Waterslide", emoji: "🎢", difficulty: "hard" },
    { name: "eyeglasses", displayName: "Eyeglasses", emoji: "👓", difficulty: "easy" },
    { name: "ceiling_fan", displayName: "Ceiling Fan", emoji: "✏️", difficulty: "medium" },
    { name: "lobster", displayName: "Lobster", emoji: "🦞", difficulty: "medium" },
    { name: "moustache", displayName: "Moustache", emoji: "🥸", difficulty: "easy" },
    { name: "carrot", displayName: "Carrot", emoji: "🥕", difficulty: "easy" },
    { name: "garden", displayName: "Garden", emoji: "🌻", difficulty: "hard" },
    { name: "police_car", displayName: "Police Car", emoji: "🚔", difficulty: "medium" },
    { name: "postcard", displayName: "Postcard", emoji: "📮", difficulty: "medium" },
    { name: "necklace", displayName: "Necklace", emoji: "📿", difficulty: "medium" },
    { name: "helmet", displayName: "Helmet", emoji: "⛑️", difficulty: "easy" },
    { name: "blackberry", displayName: "Blackberry", emoji: "✏️", difficulty: "medium" },
    { name: "beach", displayName: "Beach", emoji: "🏖️", difficulty: "medium" },
    { name: "golf_club", displayName: "Golf Club", emoji: "⛳", difficulty: "medium" },
    { name: "car", displayName: "Car", emoji: "🚗", difficulty: "easy" },
    { name: "panda", displayName: "Panda", emoji: "🐼", difficulty: "easy" },
    { name: "alarm_clock", displayName: "Alarm Clock", emoji: "⏰", difficulty: "easy" },
    { name: "t-shirt", displayName: "T-Shirt", emoji: "👕", difficulty: "easy" },
    { name: "dog", displayName: "Dog", emoji: "🐕", difficulty: "easy" },
    { name: "bread", displayName: "Bread", emoji: "🍞", difficulty: "easy" },
    { name: "wine_glass", displayName: "Wine Glass", emoji: "🍷", difficulty: "easy" },
    { name: "lighter", displayName: "Lighter", emoji: "🔥", difficulty: "medium" },
    { name: "flower", displayName: "Flower", emoji: "🌸", difficulty: "easy" },
    { name: "bandage", displayName: "Bandage", emoji: "🩹", difficulty: "easy" },
    { name: "drill", displayName: "Drill", emoji: "✏️", difficulty: "medium" },
    { name: "butterfly", displayName: "Butterfly", emoji: "🦋", difficulty: "easy" },
    { name: "swan", displayName: "Swan", emoji: "🦢", difficulty: "medium" },
    { name: "owl", displayName: "Owl", emoji: "🦉", difficulty: "medium" },
    { name: "raccoon", displayName: "Raccoon", emoji: "🦝", difficulty: "medium" },
    { name: "squiggle", displayName: "Squiggle", emoji: "〰️", difficulty: "easy" },
    { name: "calendar", displayName: "Calendar", emoji: "📅", difficulty: "easy" },
    { name: "giraffe", displayName: "Giraffe", emoji: "🦒", difficulty: "medium" },
    { name: "elephant", displayName: "Elephant", emoji: "🐘", difficulty: "medium" },
    { name: "trumpet", displayName: "Trumpet", emoji: "🎺", difficulty: "medium" },
    { name: "rabbit", displayName: "Rabbit", emoji: "🐰", difficulty: "easy" },
    { name: "trombone", displayName: "Trombone", emoji: "🎵", difficulty: "hard" },
    { name: "sheep", displayName: "Sheep", emoji: "🐑", difficulty: "medium" },
    { name: "onion", displayName: "Onion", emoji: "🧅", difficulty: "easy" },
    { name: "church", displayName: "Church", emoji: "⛪", difficulty: "medium" },
    { name: "flip_flops", displayName: "Flip Flops", emoji: "🩴", difficulty: "easy" },
    { name: "spreadsheet", displayName: "Spreadsheet", emoji: "📊", difficulty: "hard" },
    { name: "pear", displayName: "Pear", emoji: "🍐", difficulty: "easy" },
    { name: "clock", displayName: "Clock", emoji: "🕐", difficulty: "easy" },
    { name: "roller_coaster", displayName: "Roller Coaster", emoji: "🎢", difficulty: "hard" },
    { name: "parachute", displayName: "Parachute", emoji: "🪂", difficulty: "medium" },
    { name: "kangaroo", displayName: "Kangaroo", emoji: "🦘", difficulty: "medium" },
    { name: "duck", displayName: "Duck", emoji: "🦆", difficulty: "easy" },
    { name: "remote_control", displayName: "Remote Control", emoji: "📺", difficulty: "medium" },
    { name: "compass", displayName: "Compass", emoji: "🧭", difficulty: "medium" },
    { name: "monkey", displayName: "Monkey", emoji: "🐒", difficulty: "medium" },
    { name: "rainbow", displayName: "Rainbow", emoji: "🌈", difficulty: "easy" },
    { name: "tennis_racquet", displayName: "Tennis Racquet", emoji: "🎾", difficulty: "medium" },
    { name: "lion", displayName: "Lion", emoji: "🦁", difficulty: "medium" },
    { name: "pencil", displayName: "Pencil", emoji: "✏️", difficulty: "easy" },
    { name: "string_bean", displayName: "String Bean", emoji: "✏️", difficulty: "medium" },
    { name: "oven", displayName: "Oven", emoji: "✏️", difficulty: "medium" },
    { name: "star", displayName: "Star", emoji: "⭐", difficulty: "easy" },
    { name: "cat", displayName: "Cat", emoji: "🐱", difficulty: "easy" },
    { name: "pizza", displayName: "Pizza", emoji: "🍕", difficulty: "easy" },
    { name: "soccer_ball", displayName: "Soccer Ball", emoji: "⚽", difficulty: "easy" },
    { name: "syringe", displayName: "Syringe", emoji: "💉", difficulty: "medium" },
    { name: "flying_saucer", displayName: "Flying Saucer", emoji: "🛸", difficulty: "medium" },
    { name: "eye", displayName: "Eye", emoji: "👁️", difficulty: "easy" },
    { name: "cookie", displayName: "Cookie", emoji: "🍪", difficulty: "easy" },
    { name: "floor_lamp", displayName: "Floor Lamp", emoji: "🪔", difficulty: "easy" },
    { name: "mouse", displayName: "Mouse", emoji: "🐭", difficulty: "easy" },
    { name: "toilet", displayName: "Toilet", emoji: "🚽", difficulty: "easy" },
    { name: "toaster", displayName: "Toaster", emoji: "✏️", difficulty: "easy" },
    { name: "The_Eiffel_Tower", displayName: "Eiffel Tower", emoji: "🗼", difficulty: "medium" },
    { name: "airplane", displayName: "Airplane", emoji: "✈️", difficulty: "medium" },
    { name: "stove", displayName: "Stove", emoji: "✏️", difficulty: "medium" },
    { name: "cello", displayName: "Cello", emoji: "🎻", difficulty: "hard" },
    { name: "stop_sign", displayName: "Stop Sign", emoji: "🛑", difficulty: "easy" },
    { name: "tent", displayName: "Tent", emoji: "⛺", difficulty: "easy" },
    { name: "diving_board", displayName: "Diving Board", emoji: "✏️", difficulty: "hard" },
    { name: "light_bulb", displayName: "Light Bulb", emoji: "💡", difficulty: "easy" },
    { name: "hammer", displayName: "Hammer", emoji: "🔨", difficulty: "easy" },
    { name: "scorpion", displayName: "Scorpion", emoji: "🦂", difficulty: "hard" },
    { name: "headphones", displayName: "Headphones", emoji: "🎧", difficulty: "easy" },
    { name: "basket", displayName: "Basket", emoji: "🧺", difficulty: "easy" },
    { name: "spider", displayName: "Spider", emoji: "🕷️", difficulty: "medium" },
    { name: "paper_clip", displayName: "Paper Clip", emoji: "📎", difficulty: "easy" },
    { name: "sweater", displayName: "Sweater", emoji: "🧥", difficulty: "medium" },
    { name: "ice_cream", displayName: "Ice Cream", emoji: "🍦", difficulty: "easy" },
    { name: "envelope", displayName: "Envelope", emoji: "✉️", difficulty: "easy" },
    { name: "sea_turtle", displayName: "Sea Turtle", emoji: "🐢", difficulty: "medium" },
    { name: "donut", displayName: "Donut", emoji: "🍩", difficulty: "easy" },
    { name: "hat", displayName: "Hat", emoji: "🎩", difficulty: "easy" },
    { name: "hourglass", displayName: "Hourglass", emoji: "⏳", difficulty: "easy" },
    { name: "broccoli", displayName: "Broccoli", emoji: "🥦", difficulty: "easy" },
    { name: "jacket", displayName: "Jacket", emoji: "🧥", difficulty: "medium" },
    { name: "backpack", displayName: "Backpack", emoji: "🎒", difficulty: "easy" },
    { name: "book", displayName: "Book", emoji: "📖", difficulty: "easy" },
    { name: "lightning", displayName: "Lightning", emoji: "⚡", difficulty: "easy" },
    { name: "drums", displayName: "Drums", emoji: "🥁", difficulty: "medium" },
    { name: "snowflake", displayName: "Snowflake", emoji: "❄️", difficulty: "easy" },
    { name: "radio", displayName: "Radio", emoji: "📻", difficulty: "medium" },
    { name: "banana", displayName: "Banana", emoji: "🍌", difficulty: "easy" },
    { name: "camel", displayName: "Camel", emoji: "🐫", difficulty: "medium" },
    { name: "canoe", displayName: "Canoe", emoji: "🛶", difficulty: "medium" },
    { name: "toothpaste", displayName: "Toothpaste", emoji: "✏️", difficulty: "easy" },
    { name: "chair", displayName: "Chair", emoji: "🪑", difficulty: "easy" },
    { name: "picture_frame", displayName: "Picture Frame", emoji: "🖼️", difficulty: "easy" },
    { name: "parrot", displayName: "Parrot", emoji: "🦜", difficulty: "medium" },
    { name: "sandwich", displayName: "Sandwich", emoji: "🥪", difficulty: "easy" },
    { name: "lipstick", displayName: "Lipstick", emoji: "💄", difficulty: "easy" },
    { name: "pants", displayName: "Pants", emoji: "👖", difficulty: "easy" },
    { name: "violin", displayName: "Violin", emoji: "🎻", difficulty: "medium" },
    { name: "brain", displayName: "Brain", emoji: "🧠", difficulty: "medium" },
    { name: "power_outlet", displayName: "Power Outlet", emoji: "🔌", difficulty: "easy" },
    { name: "triangle", displayName: "Triangle", emoji: "🔺", difficulty: "easy" },
    { name: "hamburger", displayName: "Hamburger", emoji: "🍔", difficulty: "easy" },
    { name: "dragon", displayName: "Dragon", emoji: "🐉", difficulty: "hard" },
    { name: "bulldozer", displayName: "Bulldozer", emoji: "✏️", difficulty: "hard" },
    { name: "cannon", displayName: "Cannon", emoji: "✏️", difficulty: "medium" },
    { name: "dolphin", displayName: "Dolphin", emoji: "🐬", difficulty: "medium" },
    { name: "zebra", displayName: "Zebra", emoji: "🦓", difficulty: "medium" },
    { name: "animal_migration", displayName: "Animal Migration", emoji: "🐦", difficulty: "hard" },
    { name: "camouflage", displayName: "Camouflage", emoji: "✏️", difficulty: "hard" },
    { name: "scissors", displayName: "Scissors", emoji: "✂️", difficulty: "easy" },
    { name: "basketball", displayName: "Basketball", emoji: "🏀", difficulty: "easy" },
    { name: "elbow", displayName: "Elbow", emoji: "✏️", difficulty: "hard" },
    { name: "umbrella", displayName: "Umbrella", emoji: "☂️", difficulty: "easy" },
    { name: "windmill", displayName: "Windmill", emoji: "✏️", difficulty: "medium" },
    { name: "table", displayName: "Table", emoji: "✏️", difficulty: "easy" },
    { name: "rifle", displayName: "Rifle", emoji: "✏️", difficulty: "medium" },
    { name: "hexagon", displayName: "Hexagon", emoji: "⬡", difficulty: "easy" },
    { name: "potato", displayName: "Potato", emoji: "🥔", difficulty: "easy" },
    { name: "anvil", displayName: "Anvil", emoji: "✏️", difficulty: "hard" },
    { name: "sword", displayName: "Sword", emoji: "⚔️", difficulty: "medium" },
    { name: "peanut", displayName: "Peanut", emoji: "🥜", difficulty: "easy" },
    { name: "axe", displayName: "Axe", emoji: "🪓", difficulty: "medium" },
    { name: "television", displayName: "Television", emoji: "📺", difficulty: "easy" },
    { name: "rhinoceros", displayName: "Rhinoceros", emoji: "🦏", difficulty: "medium" },
    { name: "baseball_bat", displayName: "Baseball Bat", emoji: "⚾", difficulty: "easy" },
    { name: "speedboat", displayName: "Speedboat", emoji: "🚤", difficulty: "medium" },
    { name: "sailboat", displayName: "Sailboat", emoji: "⛵", difficulty: "easy" },
    { name: "zigzag", displayName: "Zigzag", emoji: "〰️", difficulty: "easy" },
    { name: "garden_hose", displayName: "Garden Hose", emoji: "✏️", difficulty: "hard" },
    { name: "river", displayName: "River", emoji: "🏞️", difficulty: "medium" },
    { name: "house", displayName: "House", emoji: "🏠", difficulty: "easy" },
    { name: "pillow", displayName: "Pillow", emoji: "✏️", difficulty: "easy" },
    { name: "ant", displayName: "Ant", emoji: "🐜", difficulty: "medium" },
    { name: "tiger", displayName: "Tiger", emoji: "🐯", difficulty: "medium" },
    { name: "stairs", displayName: "Stairs", emoji: "✏️", difficulty: "easy" },
    { name: "cooler", displayName: "Cooler", emoji: "🧊", difficulty: "medium" },
    { name: "see_saw", displayName: "See Saw", emoji: "✏️", difficulty: "medium" },
    { name: "piano", displayName: "Piano", emoji: "🎹", difficulty: "medium" },
    { name: "fireplace", displayName: "Fireplace", emoji: "🔥", difficulty: "medium" },
    { name: "popsicle", displayName: "Popsicle", emoji: "✏️", difficulty: "easy" },
    { name: "dumbbell", displayName: "Dumbbell", emoji: "🏋️", difficulty: "easy" },
    { name: "mailbox", displayName: "Mailbox", emoji: "📫", difficulty: "easy" },
    { name: "barn", displayName: "Barn", emoji: "✏️", difficulty: "medium" },
    { name: "hot_tub", displayName: "Hot Tub", emoji: "♨️", difficulty: "medium" },
    { name: "teddy-bear", displayName: "Teddy Bear", emoji: "🧸", difficulty: "easy" },
    { name: "fork", displayName: "Fork", emoji: "🍴", difficulty: "easy" },
    { name: "dishwasher", displayName: "Dishwasher", emoji: "✏️", difficulty: "medium" },
    { name: "peas", displayName: "Peas", emoji: "✏️", difficulty: "medium" },
    { name: "hot_air_balloon", displayName: "Hot Air Balloon", emoji: "🎈", difficulty: "medium" },
    { name: "keyboard", displayName: "Keyboard", emoji: "⌨️", difficulty: "medium" },
    { name: "microwave", displayName: "Microwave", emoji: "✏️", difficulty: "easy" },
    { name: "wheel", displayName: "Wheel", emoji: "☸️", difficulty: "easy" },
    { name: "fire_hydrant", displayName: "Fire Hydrant", emoji: "🧯", difficulty: "easy" },
    { name: "van", displayName: "Van", emoji: "🚐", difficulty: "medium" },
    { name: "camera", displayName: "Camera", emoji: "📷", difficulty: "easy" },
    { name: "whale", displayName: "Whale", emoji: "🐋", difficulty: "medium" },
    { name: "candle", displayName: "Candle", emoji: "🕯️", difficulty: "easy" },
    { name: "octopus", displayName: "Octopus", emoji: "🐙", difficulty: "medium" },
    { name: "pig", displayName: "Pig", emoji: "🐷", difficulty: "easy" },
    { name: "swing_set", displayName: "Swing Set", emoji: "✏️", difficulty: "medium" },
    { name: "helicopter", displayName: "Helicopter", emoji: "🚁", difficulty: "medium" },
    { name: "saxophone", displayName: "Saxophone", emoji: "🎷", difficulty: "medium" },
    { name: "passport", displayName: "Passport", emoji: "✏️", difficulty: "medium" },
    { name: "bat", displayName: "Bat", emoji: "🦇", difficulty: "medium" },
    { name: "ambulance", displayName: "Ambulance", emoji: "🚑", difficulty: "medium" },
    { name: "diamond", displayName: "Diamond", emoji: "💎", difficulty: "easy" },
    { name: "goatee", displayName: "Goatee", emoji: "✏️", difficulty: "hard" },
    { name: "fence", displayName: "Fence", emoji: "✏️", difficulty: "easy" },
    { name: "grass", displayName: "Grass", emoji: "🌱", difficulty: "easy" },
    { name: "mermaid", displayName: "Mermaid", emoji: "🧜", difficulty: "hard" },
    { name: "motorbike", displayName: "Motorbike", emoji: "🏍️", difficulty: "medium" },
    { name: "microphone", displayName: "Microphone", emoji: "🎤", difficulty: "easy" },
    { name: "toe", displayName: "Toe", emoji: "✏️", difficulty: "hard" },
    { name: "cactus", displayName: "Cactus", emoji: "🌵", difficulty: "easy" },
    { name: "nail", displayName: "Nail", emoji: "✏️", difficulty: "medium" },
    { name: "telephone", displayName: "Telephone", emoji: "☎️", difficulty: "easy" },
    { name: "hand", displayName: "Hand", emoji: "✋", difficulty: "medium" },
    { name: "squirrel", displayName: "Squirrel", emoji: "🐿️", difficulty: "medium" },
    { name: "streetlight", displayName: "Streetlight", emoji: "🏮", difficulty: "easy" },
    { name: "bed", displayName: "Bed", emoji: "🛏️", difficulty: "easy" },
    { name: "firetruck", displayName: "Firetruck", emoji: "🚒", difficulty: "medium" }
];

// Lookup map for fast access by name
const CATEGORY_MAP = {};
CATEGORIES.forEach(function(cat, i) {
    CATEGORY_MAP[cat.name] = { index: i, displayName: cat.displayName, emoji: cat.emoji, difficulty: cat.difficulty };
});
